Перед вами введение в синтаксис PyTorch, заимствованное с [официального сайта](https://pytorch.org/tutorials/index.html) фрэймворка

По [данной](https://rickwierenga.com/blog/machine%20learning/numpy-vs-pytorch-linalg.html) ссылке находится также очень познавательная статья о сравнении библиотек `numpy` и `PyTorch` 


In [1]:
%matplotlib inline


Introduction to PyTorch
***********************

Introduction to Torch's tensor library
======================================

All of deep learning is computations on tensors, which are
generalizations of a matrix that can be indexed in more than 2
dimensions. We will see exactly what this means in-depth later. First,
let's look what we can do with tensors.



In [9]:
# Author: Robert Guthrie

import torch

torch.manual_seed(1)

Creating Tensors
~~~~~~~~~~~~~~~~

Tensors can be created from Python lists with the torch.tensor()
function.




In [10]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a.astype(float)

array([1., 2., 3.])

In [11]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


What is a 3D tensor anyway? Think about it like this. If you have a
vector, indexing into the vector gives you a scalar. If you have a
matrix, indexing into the matrix gives you a vector. If you have a 3D
tensor, then indexing into the tensor gives you a matrix!

A note on terminology:
when I say "tensor" in this tutorial, it refers
to any torch.Tensor object. Matrices and vectors are special cases of
torch.Tensors, where their dimension is 2 and 1 respectively. When I am
talking about 3D tensors, I will explicitly use the term "3D tensor".




In [12]:
np.array([1,2,3])[0]

1

In [13]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


You can also create tensors of other data types. To create a tensor of integer types, try
torch.tensor([[1, 2], [3, 4]]) (where all elements in the list are integers).
You can also specify a data type by passing in ``dtype=torch.data_type``.
Check the documentation for more data types, but
Float and Long will be the most common.




You can create a tensor with random data and the supplied dimensionality
with torch.randn()




In [14]:
x = torch.randn((3, 4, 5))
print(x.shape)

torch.Size([3, 4, 5])


In [15]:
x

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])

Operations with Tensors
~~~~~~~~~~~~~~~~~~~~~~~

You can operate on tensors in the ways you would expect.



In [16]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


See `the documentation <https://pytorch.org/docs/torch.html>`__ for a
complete list of the massive number of operations available to you. They
expand beyond just mathematical operations.

One helpful operation that we will make use of later is concatenation.




In [17]:
a = np.array([1,2,3])
b = np.array([1,2,3])

np.concatenate([a, b])




array([1, 2, 3, 1, 2, 3])

In [19]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1], dim=0)
print(z_1.shape)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], dim=1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
#torch.cat([x_1, x_2])

torch.Size([5, 5])
tensor([[-0.6101, -1.2960, -0.9434,  1.8782, -0.5666,  0.4016, -0.1153,  0.3170],
        [ 0.6684,  1.1628, -0.3229,  0.5629,  0.8662, -0.3528,  0.3482,  1.1371]])


__Tensor__ -- это такой же массив, как и в __numpy.array__, размерность и тип данных которого мы можем задать. Tensor в отличие от numpy.array может вычисляться на __GPU__.

In [ ]:
print(x_1, '\n\n', y_1)

tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317]]) 

 tensor([[-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])


In [ ]:
z_1

tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317],
        [-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])

In [ ]:
import numpy as np
import torch

In [20]:
N = 100
D_in = 50

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

x = np.random.randn(N, D_in)
x_torch = torch.randn((N, D_in, 2), device=device, dtype=dtype)
print(x_torch.shape)
torch.tensor([1,2,3], device=device)

torch.Size([100, 50, 2])


tensor([1, 2, 3])

In [ ]:
x

array([[ 0.82990655, -0.43129858,  0.52267353, ...,  0.08369813,
        -0.9696587 , -1.14777386],
       [ 0.35660587, -1.70570001, -0.73054628, ...,  0.7054356 ,
        -0.19175958, -1.32043997],
       [-1.14953086, -0.71218215,  0.60798272, ..., -0.27804389,
         0.06727785, -0.05241278],
       ...,
       [-0.12601376, -0.40369822,  1.86995637, ...,  0.19873046,
         0.47444769, -1.64016111],
       [ 1.14986547, -1.1955551 ,  0.08088557, ...,  1.3578271 ,
         0.12555348,  1.26148237],
       [ 0.68575166, -0.80300454,  0.64199719, ...,  0.13984849,
        -0.56120301, -0.94709401]])

In [ ]:
x_torch

In [ ]:
np.ones((N, D_in))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
x_torch = torch.Tensor(np.ones((N, D_in)))
x_torch

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

На [странице](https://pytorch.org/docs/stable/tensors.html) приведено описания различных численных форматов `torch.Tensor`

In [21]:
x_torch = torch.FloatTensor([1, 2, 3])
x_torch

tensor([1., 2., 3.])

In [22]:
x1 = torch.IntTensor([1, 2, 3])
x2 = torch.FloatTensor([3, 4, 5])

In [23]:
x1, x2

(tensor([1, 2, 3], dtype=torch.int32), tensor([3., 4., 5.]))

В PyTorch можно найти много операций, которые похожи на то, что есть в numpy :
```
- torch.add (np.add) -> сложение тензоров (поэлементное)
- torch.sub (np.subtract) -> вычитание (поэлементное)
- torch.mul (np.multiply) -> умножение скаляров / матриц (поэлементное)
- torch.mm (np.matmul) -> перемножение матриц
- torch.ones (np.ones) -> создание тензора из единиц
```

Давайте попробуем вышепересчисленные операции

In [24]:
a = torch.tensor([1,2,3])
b = torch.ones_like(a)
print(a, b)
torch.add(a, b), a.add(b)

tensor([1, 2, 3]) tensor([1, 1, 1])


(tensor([2, 3, 4]), tensor([2, 3, 4]))

In [25]:
a+b

tensor([2, 3, 4])

In [26]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [40]:
x2 = torch.FloatTensor([[7, 8], [9, 1], [2, 3]])
x2

tensor([[7., 8.],
        [9., 1.],
        [2., 3.]])

In [28]:
out = torch.mm(x1, x2)
out

tensor([[31., 19.],
        [85., 55.]])

In [29]:
x1 @ x2

tensor([[31., 19.],
        [85., 55.]])

In [30]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
print(torch.ones_like(x1))
print()
print(torch.ones_like(x2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


Reshaping Tensors
~~~~~~~~~~~~~~~~~

Use the .view() method to reshape a tensor. This method receives heavy
use, because many neural network components expect their inputs to have
a certain shape. Often you will need to reshape before passing your data
to the component.




In [32]:
x = torch.tensor([[[1,2,3],
                  [3,4,5]],
                
                [[1,2,3],
                  [3,4,5]]])
print(x.shape)
x.view(3, -1)
# x.shape

torch.Size([2, 2, 3])


tensor([[1, 2, 3, 3],
        [4, 5, 1, 2],
        [3, 3, 4, 5]])

In [ ]:
x = torch.randn(2, 3, 4)
print(x, '\n\n')
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

tensor([[[-0.8596, -2.0629,  1.2663,  0.1512],
         [ 0.1689,  1.2343, -2.5467,  0.3844],
         [-0.2252,  0.0957, -0.3816, -0.0198]],

        [[-0.4534, -0.7906, -0.0660, -0.1164],
         [ 0.0864, -0.6846, -0.2107, -0.9759],
         [-0.1652,  0.3428,  0.4568,  1.7263]]]) 


tensor([[-0.8596, -2.0629,  1.2663,  0.1512,  0.1689,  1.2343, -2.5467,  0.3844,
         -0.2252,  0.0957, -0.3816, -0.0198],
        [-0.4534, -0.7906, -0.0660, -0.1164,  0.0864, -0.6846, -0.2107, -0.9759,
         -0.1652,  0.3428,  0.4568,  1.7263]])
tensor([[-0.8596, -2.0629,  1.2663,  0.1512,  0.1689,  1.2343, -2.5467,  0.3844,
         -0.2252,  0.0957, -0.3816, -0.0198],
        [-0.4534, -0.7906, -0.0660, -0.1164,  0.0864, -0.6846, -0.2107, -0.9759,
         -0.1652,  0.3428,  0.4568,  1.7263]])


```
- torch.reshape или tensor.view (где tensor-это объект torch.tensor) -> изменения порядка элементов в тензоре, не путать с транспонированием.
```

In [34]:
print(x1, '\n\n')
x1.t()

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 




tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [35]:
x1.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [36]:
torch.reshape(x1, (-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [37]:
x1.view((-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [39]:
x1 = x1.reshape_as(x2)
x1

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [41]:
x1 = x1.type(torch.int)

print(f'x1 type: {x1.dtype} \nx2 type: {x2.dtype} \n\n')
x1 + x2

x1 type: torch.int32 
x2 type: torch.float32 




tensor([[ 8., 10.],
        [12.,  5.],
        [ 7.,  9.]])